"""Add sessional marks fields to RMark

Revision ID: 1a55d1d37cd4
Revises: 7ec723656fb5
Create Date: 2025-06-22 20:45:01.129003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a55d1d37cd4'
down_revision = '7ec723656fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_mark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sessional_report', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sessional_viva', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_mark', schema=None) as batch_op:
        batch_op.drop_column('sessional_viva')
        batch_op.drop_column('sessional_report')

    # ### end Alembic commands ###
