"""Add Student model for student management

Revision ID: 1fc7715c2fe9
Revises: ef4b5a1c2b77
Create Date: 2025-11-23 14:48:16.498061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc7715c2fe9'
down_revision = 'ef4b5a1c2b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create the student table if it doesn't exist - skip other table modifications that cause issues
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'student' not in tables:
        op.create_table('student',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('batch', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('student', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_student_student_id'), ['student_id'], unique=True)
    else:
        # Table already exists, just ensure index exists
        indexes = [idx['name'] for idx in inspector.get_indexes('student')]
        if 'ix_student_student_id' not in indexes:
            with op.batch_alter_table('student', schema=None) as batch_op:
                batch_op.create_index(batch_op.f('ix_student_student_id'), ['student_id'], unique=True)

    # Skip modifications to other tables - they're false positives from autogenerate
    # The foreign keys and constraints on class_split_invite and course_review are already correct

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the student table
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_student_id'))

    op.drop_table('student')
    # ### end Alembic commands ###
