"""Add batch and curriculum_id to RSession model

Revision ID: 25f4038f2131
Revises: e956650d1bd6
Create Date: 2025-11-23 19:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f4038f2131'
down_revision = 'e956650d1bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('curriculum_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_session', schema=None) as batch_op:
        batch_op.drop_column('curriculum_id')
        batch_op.drop_column('batch')

    # ### end Alembic commands ###
