"""Add rationale, CLO, and content fields to Course model

Revision ID: 2bbe69657ef3
Revises: 4f6460017bce
Create Date: 2025-11-23 16:03:34.981032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbe69657ef3'
down_revision = '4f6460017bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add rationale, CLO, and content fields to course table
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rationale', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('clo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('clo')
        batch_op.drop_column('rationale')

    # ### end Alembic commands ###
