"""Add CurriculumYearTerm model for batch and academic session per year/term

Revision ID: 300b6e36633d
Revises: c2f3a8fa9062
Create Date: 2025-11-27 10:43:23.243015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300b6e36633d'
down_revision = 'c2f3a8fa9062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_year_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('academic_session', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'year', 'term', name='uq_curriculum_year_term')
    )
    # Note: Removed unnecessary foreign key constraint changes on duty_assignment table
    # that were auto-detected but not needed for this migration

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curriculum_year_term')
    # ### end Alembic commands ###
