"""Update Course: add content_section_a, content_section_b, and structured CLO storage

Revision ID: 34434da96ea5
Revises: 2bbe69657ef3
Create Date: 2025-11-23 16:21:27.130725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34434da96ea5'
down_revision = '2bbe69657ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Update course table: add content_section_a and content_section_b, remove content
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_section_a', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_section_b', sa.Text(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.drop_column('content_section_b')
        batch_op.drop_column('content_section_a')

    # ### end Alembic commands ###
