"""Add viva field to RMark model

Revision ID: 3a18b98f8af3
Revises: 864375fe2549
Create Date: 2025-07-30 19:11:09.877649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a18b98f8af3'
down_revision = '864375fe2549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_mark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viva', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_mark', schema=None) as batch_op:
        batch_op.drop_column('viva')

    # ### end Alembic commands ###
