"""Change Curriculum date from Date to String

Revision ID: 4f6460017bce
Revises: 5e1c7d06d5d9
Create Date: 2025-11-23 15:53:45.861924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6460017bce'
down_revision = '5e1c7d06d5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Change curriculum.date from Date to String
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
