"""Add status to student course registration and course registration invite model

Revision ID: 51db5e71c3ac
Revises: 54e4a8c279ae
Create Date: 2025-11-25 19:57:39.275420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51db5e71c3ac'
down_revision = '54e4a8c279ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before creating
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'course_registration_invite' not in tables:
        op.create_table('course_registration_invite',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('registration_id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('coordinator_teacher_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('responded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['coordinator_teacher_id'], ['teacher.id'], ),
        sa.ForeignKeyConstraint(['registration_id'], ['student_course_registration.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Check if status column exists before adding
    columns = [col['name'] for col in inspector.get_columns('student_course_registration')]
    if 'status' not in columns:
        with op.batch_alter_table('student_course_registration', schema=None) as batch_op:
            batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course_registration', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('course_registration_invite')
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course_registration', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('course_registration_invite')
    # ### end Alembic commands ###
