"""Add hall to student

Revision ID: 54e4a8c279ae
Revises: add_course_outline_cols
Create Date: 2025-11-25 19:15:08.598048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e4a8c279ae'
down_revision = 'add_course_outline_cols'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hall', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('hall')

    # ### end Alembic commands ###
