"""Add core_optional and syllabus_year to Course model

Revision ID: 56f8a606e4a7
Revises: 1fc7715c2fe9
Create Date: 2025-11-23 15:30:20.255083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f8a606e4a7'
down_revision = '1fc7715c2fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add new columns to course table
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('core_optional', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('syllabus_year', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('syllabus_year')
        batch_op.drop_column('core_optional')

    # ### end Alembic commands ###
