"""Add CourseSessionAssignment model for automatic Session creation from Curriculum

Revision ID: 57acffc05bc0
Revises: 62d949d1853d
Create Date: 2025-11-27 11:24:15.419868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57acffc05bc0'
down_revision = '62d949d1853d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_session_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('academic_session', sa.String(length=50), nullable=True),
    sa.Column('session_created', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'teacher_id', 'section', 'year', 'term', 'batch', name='uq_course_session_assignment')
    )
    # Remove server_default after table creation for SQLite compatibility
    with op.batch_alter_table('course_session_assignment', schema=None) as batch_op:
        batch_op.alter_column('session_created', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_session_assignment')
    # ### end Alembic commands ###
