"""Update Curriculum: remove description, change academic_year to date, add applicable_batches

Revision ID: 5e1c7d06d5d9
Revises: ffe0e0bd9d38
Create Date: 2025-11-23 15:45:22.321938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1c7d06d5d9'
down_revision = 'ffe0e0bd9d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Update curriculum table: remove description and academic_year, add date and applicable_batches
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('applicable_batches', sa.Text(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('academic_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('applicable_batches')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
