"""Allow same course code in different curricula by making it unique per curriculum

Revision ID: 62d949d1853d
Revises: 300b6e36633d
Create Date: 2025-11-27 10:57:33.812316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d949d1853d'
down_revision = '300b6e36633d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support dropping column-level unique constraints directly.
    # We need to recreate the table without the unique constraint on course_code,
    # and add a composite unique constraint on (curriculum_id, course_code).
    
    conn = op.get_bind()
    
    # Check if we're using SQLite
    if conn.dialect.name == 'sqlite':
        # Recreate table without column-level unique constraint on course_code
        # Step 1: Create new table without unique constraint on course_code
        op.create_table('course_new',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('curriculum_id', sa.Integer(), nullable=True),
            sa.Column('course_code', sa.String(20), nullable=False),
            sa.Column('course_name', sa.String(100), nullable=False),
            sa.Column('credit', sa.Float(), nullable=False),
            sa.Column('course_type', sa.String(20), nullable=False),
            sa.Column('category', sa.String(20), nullable=False),
            sa.Column('core_optional', sa.String(20), nullable=True),
            sa.Column('syllabus_year', sa.String(20), nullable=True),
            sa.Column('offered', sa.Boolean(), nullable=False),
            sa.Column('year', sa.String(50), nullable=True),
            sa.Column('term', sa.String(50), nullable=True),
            sa.Column('rationale', sa.Text(), nullable=True),
            sa.Column('clo', sa.Text(), nullable=True),
            sa.Column('content_section_a', sa.Text(), nullable=True),
            sa.Column('content_section_b', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('curriculum_id', 'course_code', name='uq_curriculum_course_code')
        )
        
        # Step 2: Copy data from old table to new table
        conn.execute(sa.text("""
            INSERT INTO course_new 
            SELECT id, curriculum_id, course_code, course_name, credit, course_type, 
                   category, core_optional, syllabus_year, offered, year, term, 
                   rationale, clo, content_section_a, content_section_b
            FROM course
        """))
        
        # Step 3: Drop old table
        op.drop_table('course')
        
        # Step 4: Rename new table to original name
        op.rename_table('course_new', 'course')
    else:
        # For other databases (MySQL, PostgreSQL), we can use batch_alter_table
        with op.batch_alter_table('course', schema=None) as batch_op:
            # Drop the unique constraint on course_code if it exists as an index
            # Note: This is a simplified approach - may need adjustment for specific database
            try:
                batch_op.drop_index('ix_course_course_code')
            except:
                pass
            batch_op.create_unique_constraint('uq_curriculum_course_code', ['curriculum_id', 'course_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Check if we're using SQLite
    if conn.dialect.name == 'sqlite':
        # Recreate table with unique constraint on course_code
        # Step 1: Create new table with unique constraint on course_code
        op.create_table('course_new',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('curriculum_id', sa.Integer(), nullable=True),
            sa.Column('course_code', sa.String(20), nullable=False),
            sa.Column('course_name', sa.String(100), nullable=False),
            sa.Column('credit', sa.Float(), nullable=False),
            sa.Column('course_type', sa.String(20), nullable=False),
            sa.Column('category', sa.String(20), nullable=False),
            sa.Column('core_optional', sa.String(20), nullable=True),
            sa.Column('syllabus_year', sa.String(20), nullable=True),
            sa.Column('offered', sa.Boolean(), nullable=False),
            sa.Column('year', sa.String(50), nullable=True),
            sa.Column('term', sa.String(50), nullable=True),
            sa.Column('rationale', sa.Text(), nullable=True),
            sa.Column('clo', sa.Text(), nullable=True),
            sa.Column('content_section_a', sa.Text(), nullable=True),
            sa.Column('content_section_b', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('course_code')
        )
        
        # Step 2: Copy data from old table to new table
        conn.execute(sa.text("""
            INSERT INTO course_new 
            SELECT id, curriculum_id, course_code, course_name, credit, course_type, 
                   category, core_optional, syllabus_year, offered, year, term, 
                   rationale, clo, content_section_a, content_section_b
            FROM course
        """))
        
        # Step 3: Drop old table
        op.drop_table('course')
        
        # Step 4: Rename new table to original name
        op.rename_table('course_new', 'course')
    else:
        # For other databases
        with op.batch_alter_table('course', schema=None) as batch_op:
            batch_op.drop_constraint('uq_curriculum_course_code', type_='unique')
            batch_op.create_index('ix_course_course_code', ['course_code'], unique=True)

    # ### end Alembic commands ###
