"""Add batch field to DutyAssignment model

Revision ID: 6e5ee75b3dc8
Revises: 89d2e0140134
Create Date: 2025-11-25 20:13:15.671683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5ee75b3dc8'
down_revision = '89d2e0140134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.drop_column('batch')

    # ### end Alembic commands ###
