"""Add course_code field to Session model

Revision ID: 864375fe2549
Revises: 1a55d1d37cd4
Create Date: 2025-07-07 16:23:58.105700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864375fe2549'
down_revision = '1a55d1d37cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.drop_column('course_code')

    # ### end Alembic commands ###
