"""Add DutyAssignment model for head duty assignments

Revision ID: 89d2e0140134
Revises: 51db5e71c3ac
Create Date: 2025-11-25 20:04:01.635144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d2e0140134'
down_revision = '51db5e71c3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('course_name', sa.String(length=150), nullable=True),
    sa.Column('academic_session', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('term', sa.String(length=20), nullable=True),
    sa.Column('duty_type', sa.String(length=50), nullable=False),
    sa.Column('assigned_teacher_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_teacher_id'], ['teacher.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.create_index('idx_duty_course_session', ['course_id', 'academic_session', 'year', 'term', 'duty_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.drop_index('idx_duty_course_session')

    op.drop_table('duty_assignment')
    # ### end Alembic commands ###
