"""Add ExamPaperEvaluatorAssignment model

Revision ID: 8df51e223e14
Revises: e595243439fa
Create Date: 2025-12-27 09:57:10.985676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df51e223e14'
down_revision = 'e595243439fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_paper_evaluator_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=10), nullable=False),
    sa.Column('assigned_teacher_id', sa.Integer(), nullable=False),
    sa.Column('academic_session', sa.String(length=50), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('exam_paper_evaluation_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_teacher_id'], ['teacher.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['exam_paper_evaluation_id'], ['exam_paper_evaluation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'part', 'academic_session', 'year', 'term', name='uq_evaluator_assignment')
    )
    op.drop_table('_alembic_tmp_course_outline')
    with op.batch_alter_table('course_outline', schema=None) as batch_op:
        batch_op.alter_column('credit_value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('course_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('level_term_section',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_outline', schema=None) as batch_op:
        batch_op.alter_column('level_term_section',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('course_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('credit_value',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_course_outline',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.Column('course_objectives', sa.TEXT(), nullable=True),
    sa.Column('course_summary', sa.TEXT(), nullable=True),
    sa.Column('prerequisites', sa.VARCHAR(length=200), nullable=True),
    sa.Column('contact_hours', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cie_marks', sa.VARCHAR(length=50), nullable=True),
    sa.Column('smee_marks', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lesson_plan', sa.TEXT(), nullable=True),
    sa.Column('course_content_summary', sa.TEXT(), nullable=True),
    sa.Column('clo_plo_mapping', sa.TEXT(), nullable=True),
    sa.Column('assessment_strategy', sa.TEXT(), nullable=True),
    sa.Column('assessment_techniques', sa.TEXT(), nullable=True),
    sa.Column('rubrics', sa.TEXT(), nullable=True),
    sa.Column('grading_policy', sa.TEXT(), nullable=True),
    sa.Column('evaluation_policy', sa.TEXT(), nullable=True),
    sa.Column('cie_breakdown', sa.TEXT(), nullable=True),
    sa.Column('smee_breakdown', sa.TEXT(), nullable=True),
    sa.Column('textbooks', sa.TEXT(), nullable=True),
    sa.Column('reference_books', sa.TEXT(), nullable=True),
    sa.Column('other_resources', sa.TEXT(), nullable=True),
    sa.Column('course_file_components', sa.TEXT(), nullable=True),
    sa.Column('make_up_procedures', sa.TEXT(), nullable=True),
    sa.Column('other_issues', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('credit_value', sa.VARCHAR(length=20), nullable=True),
    sa.Column('course_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('level_term_section', sa.VARCHAR(length=100), nullable=True),
    sa.Column('clo_data', sa.TEXT(), nullable=True),
    sa.Column('plo_mapping', sa.TEXT(), nullable=True),
    sa.Column('student_access_enabled', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_session.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exam_paper_evaluator_assignment')
    # ### end Alembic commands ###
