"""Add year and term fields to Course model

Revision ID: 9fc6c47cab0d
Revises: 34434da96ea5
Create Date: 2025-11-23 16:51:05.666428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc6c47cab0d'
down_revision = '34434da96ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('term', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('term')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
