"""Allow TA assignments with student reference

Revision ID: aa974a9e0d20
Revises: 6e5ee75b3dc8
Create Date: 2025-11-25 20:41:57.980484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa974a9e0d20'
down_revision = '6e5ee75b3dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.alter_column('assigned_teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_duty_assignment_student', 'student', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_duty_assignment_student', type_='foreignkey')
        batch_op.alter_column('assigned_teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
