"""Add missing columns to course_outline table

Revision ID: add_course_outline_cols
Revises: add_course_outline
Create Date: 2025-11-24 23:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_course_outline_cols'
down_revision = 'add_course_outline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect, text
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Get existing columns
    if 'course_outline' in inspector.get_table_names():
        existing_columns = [col['name'] for col in inspector.get_columns('course_outline')]
        
        with op.batch_alter_table('course_outline', schema=None) as batch_op:
            if 'course_content_summary' not in existing_columns:
                batch_op.add_column(sa.Column('course_content_summary', sa.Text(), nullable=True))
            if 'clo_plo_mapping' not in existing_columns:
                batch_op.add_column(sa.Column('clo_plo_mapping', sa.Text(), nullable=True))
            if 'evaluation_policy' not in existing_columns:
                batch_op.add_column(sa.Column('evaluation_policy', sa.Text(), nullable=True))
            if 'cie_breakdown' not in existing_columns:
                batch_op.add_column(sa.Column('cie_breakdown', sa.Text(), nullable=True))
            if 'smee_breakdown' not in existing_columns:
                batch_op.add_column(sa.Column('smee_breakdown', sa.Text(), nullable=True))
            if 'course_file_components' not in existing_columns:
                batch_op.add_column(sa.Column('course_file_components', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_outline', schema=None) as batch_op:
        batch_op.drop_column('course_file_components')
        batch_op.drop_column('smee_breakdown')
        batch_op.drop_column('cie_breakdown')
        batch_op.drop_column('evaluation_policy')
        batch_op.drop_column('clo_plo_mapping')
        batch_op.drop_column('course_content_summary')
    # ### end Alembic commands ###

