"""Add CourseOutline model

Revision ID: add_course_outline
Revises: 25f4038f2131
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_course_outline'
down_revision = '25f4038f2131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table already exists (for SQLite compatibility)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'course_outline' in inspector.get_table_names():
        # Table already exists, skip creation
        return
    
    op.create_table('course_outline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_objectives', sa.Text(), nullable=True),
    sa.Column('course_summary', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.String(length=200), nullable=True),
    sa.Column('contact_hours', sa.String(length=50), nullable=True),
    sa.Column('cie_marks', sa.String(length=50), nullable=True),
    sa.Column('smee_marks', sa.String(length=50), nullable=True),
    sa.Column('lesson_plan', sa.Text(), nullable=True),
    sa.Column('assessment_strategy', sa.Text(), nullable=True),
    sa.Column('assessment_techniques', sa.Text(), nullable=True),
    sa.Column('rubrics', sa.Text(), nullable=True),
    sa.Column('grading_policy', sa.Text(), nullable=True),
    sa.Column('textbooks', sa.Text(), nullable=True),
    sa.Column('reference_books', sa.Text(), nullable=True),
    sa.Column('other_resources', sa.Text(), nullable=True),
    sa.Column('make_up_procedures', sa.Text(), nullable=True),
    sa.Column('other_issues', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['class_session.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_outline')
    # ### end Alembic commands ###

