"""Add ActiveSemesterConfig model for active semester management

Revision ID: a4b5c6d7e8f9
Revises: 8df51e223e14
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b5c6d7e8f9'
down_revision = '198dab01253c'  # Changed from 8df51e223e14 to 198dab01253c (latest in branch)
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table already exists
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'active_semester_config' not in inspector.get_table_names():
        op.create_table('active_semester_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('academic_session', sa.String(length=50), nullable=False),
        sa.Column('year', sa.String(length=50), nullable=False),
        sa.Column('term', sa.String(length=50), nullable=False),
        sa.Column('batch', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('activated_by', sa.String(length=100), nullable=True),
        sa.Column('activated_at', sa.DateTime(), nullable=False),
        sa.Column('deactivated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_active_semester', 'active_semester_config', ['academic_session', 'year', 'term', 'batch', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_active_semester', table_name='active_semester_config')
    op.drop_table('active_semester_config')
    # ### end Alembic commands ###

