"""Add call_sign and bank_account_no to teacher

Revision ID: a1b2c3d4e5f6
Revises: 57acffc05bc0
Create Date: 2025-12-07 12:20:12.856338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '57acffc05bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_sign', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_account_no', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('bank_account_no')
        batch_op.drop_column('call_sign')

    # ### end Alembic commands ###

