"""add curriculator syllabus tables

Revision ID: b1f220be6847
Revises: add_course_question_tables
Create Date: 2026-01-28 23:38:22.767329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f220be6847'
down_revision = 'add_course_question_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabus_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('applicable_batches', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syllabus_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('part_key', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['syllabus_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'part_key', name='uq_syllabus_part_doc_key')
    )
    op.create_table('syllabus_course_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('course_name', sa.String(length=200), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('year_term', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['syllabus_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syllabus_author_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_entry_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_entry_id'], ['syllabus_course_entry.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_entry_id', 'teacher_id', name='uq_syllabus_author_entry_teacher')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syllabus_author_assignment')
    op.drop_table('syllabus_course_entry')
    op.drop_table('syllabus_part')
    op.drop_table('syllabus_document')
    # ### end Alembic commands ###
