"""Add AlumniSurveyResponse

Revision ID: bb92084bacee
Revises: add_psac_committee
Create Date: 2026-02-15 00:30:00.967315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb92084bacee'
down_revision = 'add_psac_committee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_survey_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('batch', sa.String(length=50), nullable=True),
    sa.Column('graduation_year', sa.String(length=20), nullable=True),
    sa.Column('degree_completed', sa.JSON(), nullable=True),
    sa.Column('current_designation', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('employment_sector', sa.String(length=100), nullable=True),
    sa.Column('employment_sector_other', sa.String(length=100), nullable=True),
    sa.Column('is_enrolled', sa.Boolean(), nullable=True),
    sa.Column('enrollment_time', sa.String(length=50), nullable=True),
    sa.Column('curriculum_balance', sa.Integer(), nullable=True),
    sa.Column('knowledge_skills', sa.Integer(), nullable=True),
    sa.Column('critical_thinking', sa.Integer(), nullable=True),
    sa.Column('ethical_values', sa.Integer(), nullable=True),
    sa.Column('gen_ed_usefulness', sa.Integer(), nullable=True),
    sa.Column('assessment_methods', sa.Integer(), nullable=True),
    sa.Column('moot_court', sa.Integer(), nullable=True),
    sa.Column('library_resources', sa.Integer(), nullable=True),
    sa.Column('faculty_support', sa.Integer(), nullable=True),
    sa.Column('career_counseling', sa.Integer(), nullable=True),
    sa.Column('academic_calendar', sa.Integer(), nullable=True),
    sa.Column('admin_staff', sa.Integer(), nullable=True),
    sa.Column('time_to_first_job', sa.String(length=50), nullable=True),
    sa.Column('job_market_competitiveness', sa.String(length=50), nullable=True),
    sa.Column('skills_acquired', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumni_survey_response')
    # ### end Alembic commands ###
