"""Add thesis fields to RMark

Revision ID: d15c240d9970
Revises: 198dab01253c
Create Date: 2025-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15c240d9970'
down_revision = '198dab01253c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_mark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thesis_evaluation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('presentation', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_mark', schema=None) as batch_op:
        batch_op.drop_column('presentation')
        batch_op.drop_column('thesis_evaluation')

    # ### end Alembic commands ###

