"""Add student_access_enabled field to CourseOutline and create CourseFileUpload model

Revision ID: db88a10c33a9
Revises: 30a063eccd86
Create Date: 2025-12-26 20:43:02.384640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db88a10c33a9'
down_revision = '30a063eccd86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before creating
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'course_file_upload' not in tables:
        op.create_table('course_file_upload',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('session_id', sa.Integer(), nullable=False),
            sa.Column('teacher_id', sa.Integer(), nullable=False),
            sa.Column('file_name', sa.String(length=255), nullable=False),
            sa.Column('file_path', sa.String(length=500), nullable=False),
            sa.Column('file_size', sa.Integer(), nullable=True),
            sa.Column('file_type', sa.String(length=50), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('student_access_enabled', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['session_id'], ['class_session.id'], ),
            sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # Check if column exists before adding
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('course_outline')]
    
    if 'student_access_enabled' not in columns:
        op.add_column('course_outline', sa.Column('student_access_enabled', sa.Boolean(), nullable=False, server_default='0'))
    
    # Skip column type changes for now to avoid issues
    # These can be done in a separate migration if needed

    with op.batch_alter_table('exam_scrutinizer_invite', schema=None) as batch_op:
        batch_op.alter_column('is_complete',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_scrutinizer_invite', schema=None) as batch_op:
        batch_op.alter_column('is_complete',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('course_outline', schema=None) as batch_op:
        batch_op.alter_column('level_term_section',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('course_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('credit_value',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('student_access_enabled')

    op.drop_table('course_file_upload')
    # ### end Alembic commands ###
