"""add_theme_field_to_user

Revision ID: e595243439fa
Revises: db88a10c33a9
Create Date: 2025-12-26 23:01:54.956260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e595243439fa'
down_revision = 'db88a10c33a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('users', sa.Column('theme', sa.String(length=50), nullable=True, server_default='default'))
    except Exception:
        # Column might already exist
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('users', 'theme')
    except Exception:
        # Column might not exist
        pass
    # ### end Alembic commands ###
