"""Add assessment_absent field to ClassStudent

Revision ID: e6e11ab3e3eb
Revises: 9fc6c47cab0d
Create Date: 2025-11-23 18:05:35.625416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e11ab3e3eb'
down_revision = '9fc6c47cab0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_absent', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_student', schema=None) as batch_op:
        batch_op.drop_column('assessment_absent')

    # ### end Alembic commands ###
