"""Add offered field to Course model

Revision ID: e956650d1bd6
Revises: e6e11ab3e3eb
Create Date: 2025-11-23 19:10:50.135982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e956650d1bd6'
down_revision = 'e6e11ab3e3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offered', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('offered')

    # ### end Alembic commands ###
