"""Add Curriculum model and curriculum_id to Course

Revision ID: ffe0e0bd9d38
Revises: 56f8a606e4a7
Create Date: 2025-11-23 15:39:51.858564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe0e0bd9d38'
down_revision = '56f8a606e4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create curriculum table
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Add curriculum_id to course table
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curriculum_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_course_curriculum', 'curriculum', ['curriculum_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_curriculum', type_='foreignkey')
        batch_op.drop_column('curriculum_id')

    op.drop_table('curriculum')
    # ### end Alembic commands ###
